# Configurações para estabilizar o build
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Isso ajuda o Gradle a ignorar versões de Java incompatíveis em alguns casos
org.gradle.java.installations.auto-detect=true
